made solution
Sashk52/jv-hw-dao3 pull request #8
Opened 2021-01-25 21:01 UTC by Sashk52

2021-01-25 21:25 UTC, Fedich09 approved these changes

2021-01-25 21:25 UTC, Fedich09 commented on src/main/java/taxi/controller/AddDriverController.java
> +        req.getRequestDispatcher("/WEB-INF/views/drivers/login");
```suggestion
        req.getRequestDispatcher("/WEB-INF/views/drivers/login");
```
This won't work without .forward() I think

2021-01-26 08:35 UTC, RomanDubovskyi requested changes
you don't have filter in PR, this task is not fully completed

2021-01-26 08:35 UTC, RomanDubovskyi commented on src/main/webapp/WEB-INF/views/cars/driver/all.jsp
> +--%>
remove autogenerated comment

2021-01-26 09:14 UTC, Sashk52 commented on src/main/webapp/WEB-INF/views/cars/driver/all.jsp
> +--%>
done

2021-01-26 13:17 UTC, closed without merging